#pragma once
#include <vector>

class Conway {
private:
    // Legg til de medlemsvariablene og hjelpefunksjonene du trenger
    std::vector<std::vector<bool>> canvas;
    bool started;
public:
    Conway(int width, int height);
    ~Conway();

    bool isTileAlive(int row, int col) const;
    bool hasSimulationStarted() const;

    void toggleAlive(int row, int col);
    void startSimulation();

    int getNumAdjacentCells(int row, int col) const;

    void nextGeneration();

    // Turn off autogenerated copy constructor
    Conway(const Conway &) = delete;
    Conway &operator=(const Conway &) = delete;
};
